version: "3"
services:
  mysql8:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # init script
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
#      External access port 13316
      - 13316:3306
